Bookstore: connect to API
AlselwiAisha/Bookstore pull request #4
Opened 2023-09-27 18:42 UTC by AlselwiAisha

### Description:

- Use the [Bookstore API](https://www.notion.so/Bookstore-API-51ea269061f849118c65c0a53e88a739) as my backend.
- Use [axios](https://axios-http.com/docs/intro) with [createAsyncThunk](https://redux-toolkit.js.org/api/createAsyncThunk) to make my HTTP requests to the backend
- Fetch my books from the Bookstore API after the component has rendered
- Refactor my add book and remove book features to persist my changes in the server.

2023-09-27 19:21 UTC, Johnadibe requested changes
# STATUS: REQUIRED CHANGES ♻️
### Hi @AlselwiAisha👋🏽, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Highlights
✅ You used GitFlow correctly 👍🏽
✅ Linter checks passed✔️
✅ Used Axios with createAsyncThunk to make your HTTP requests to the backend✔
✅ Fetched books from the Bookstore API after the component has rendered✔
✅ Refactored add book features to persist changes in the server✔


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-27 19:21 UTC, Johnadibe commented on src/redux/books/booksSlise.js
> +      })
> - [ ] Well done, @AlselwiAisha! I've observed that when I remove a book from both the list and the API, and then refresh the browser, the state doesn't seem to reflect the change. Could you please address this? Resolving this matter will significantly enhance the user experience. 👍
> 
> [screen-capture.webm](https://github.com/AlselwiAisha/Bookstore/assets/40009354/0c869008-60d1-4535-ac73-b2440904f991)
>

2023-09-27 19:21 UTC, Johnadibe commented on src/redux/books/booksSlise.js
> +/* eslint no-param-reassign: ["error", { "props": false }] */
> - [ ] Hello @AlselwiAisha, I'd like to emphasize the importance of maintaining our linter configurations intact. Linters serve as valuable tools in our development workflow; they help us maintain consistent code quality, identify potential issues, and ensure code adherence to best practices. Disabling these linters should not be our approach. Instead, I kindly request that we address the issue at hand in a more constructive manner. By doing so, we can maintain the integrity of our coding standards while resolving any specific concerns effectively. This approach aligns with our commitment to producing high-quality code.👍🚀

2023-09-27 19:21 UTC, Johnadibe commented on src/components/AddNewBook.js
> +      alert('Fill all fields, please!');
> - [ ] I noticed that you've added the` alert()` method in your implementation. While it's a useful tool for debugging and quick testing, it's important to consider its impact on the overall user experience and code maintainability, especially in production-level code. To enhance your code, I recommend removing the `alert()` method and considering an alternative approach for handling user interactions.👍

2023-09-28 10:40 UTC, t-yanick approved these changes
# STATUS: MILESTONE APPROVED :1st_place_medal: 

Hi @AlselwiAisha , 

### Great job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Requested changes implemented 👍 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-28 10:43 UTC, merged